### ISSUE TITLE
We have found 13 Warnings.

### ISSUE THREAD

**Issue by misterAnderson90** [streeg/guillex2#2]
I'm a PhD student interested in finding security vulnerabilities in open source projects.

We found a total of 13  warnings (indicating potential vulnerabilities) when running the CogniCrypt static analyzer (*) on guillex2 (or its library dependencies). We documented each one of these issues in private gists for the sake of confidentiality (non-disclosure). 

Can you please let us know whether we can share these gists with you? We are eager to evaluate the perception of developers (e.g. severity of these warnings) and improve guillex2's security, and the quality of the reports of static analysis tools.
(*) https://github.com/CROSSINGTUD/CryptoAnalysis

**Comment by streeg** [comment]
Nice! Thanks! Talk to me in my e-mail. You can find it on my profile.
